### ISSUE TITLE
Great thing, first potential user here :-)

### ISSUE THREAD

**Issue by totti4ever** [qcasey/paperless_share#1]
Hey there, just wanted to tell that I would find it extremely great if
* you publish this on f-droid (or play, whatever is more simple)  
it's a great idea to scan the daily stuff with the phone and send it over to paperless-ng
* you actually manage to set up a pull request to jbauers paperless app and get it going with paperless-ng as well - I could imagine he could help with that!

**Comment by qcasey** [comment]
Thanks! I have never published an app on either place before but it's definitely next on my todo list. 

Bringing this over to paperless_app would be easier once the compatibility issues with ng are sorted out. It looks like that's on the way though, so I'll be contributing sooner rather than later.

**Comment by bauerj** [comment]
This looks awesome!

I would be happy to accept a PR into paperless_app. Should I ping you once I have some basic compatibility to paperless-ng? Let me know if there's anything else you would need.

**Comment by qcasey** [comment]
Thank you! Yes please do :) 

I wouldn't need much else besides that. Either way I'd be excited to have a compatible document browser. paperless_app looks slick!

**Comment by bauerj** [comment]
Hey @qcasey,

Paperless-NG support is now implemented in https://github.com/bauerj/paperless_app/commit/c5e103842f9dfff3ddc53089d1a75b026dc8eba1.

**Comment by qcasey** [comment]
Nice, thanks very much! I will test at the earliest opportunity

**Comment by qcasey** [comment]
We've got the share intent merged over at [paperless_app](https://github.com/bauerj/paperless_app) :tada:  additionally, [paperless_share is now on Google Play](https://play.google.com/store/apps/details?id=com.quinncasey.paperless_share). An FDroid release is incoming.

This repo will be maintained for my own experience, but bauerj's now has a fuller suite of features.
