### ISSUE TITLE
[Feature request] support tagging

### ISSUE THREAD

**Issue by JHthe4** [qcasey/paperless_share#11]
Hi,

it would be a nice feature if the app supported predefining a certain tag which is always used when submitting any document (e.g. a user name in my usecase). The REST endpoint natively offers this, so it would be as easy as adding an optional configuration item which would add any text entered to the "tags" form field in the post request. 

Unfortunately, I don't know any flutter myself, otherwise I'd just do it. Since this is such a simple feature, maybe it won't take you that long. Thanks a bunch for the minimalist and useful app!

Cheers

**Comment by qcasey** [comment]
This is a neat idea. I'm absolutely open to PRs but will also take a look at implementing it myself next time I'm working on this repo.

**Comment by qcasey** [comment]
It wasn't as easy as entering a value since we have to POST a valid tag ID. 

But in the next release the app will allow you to select from a list of your tags :)

**Comment by JHthe4** [comment]
Thanks for this, you're a legend! You've helped me a lot, can't wait for the next release!

**Comment by steff75** [comment]
@qcasey Thanks for the feature with the tags. Very useful, but I found a small problem.

If you have many tags and therefore a big list, it is not scrollable. This means you can't get to the tags that are further down the list. I tried it on both my smartphone and my tablet and scrolling doesn't work on either device.

Maybe you can fix this for one of the next releases. Thanks a lot!

**Comment by qcasey** [comment]
@steff75 thanks for reporting that, I'll have it fixed in the next release.
