### ISSUE TITLE
[Feature Request] associate file types with the app

### ISSUE THREAD

**Issue by NiFNi** [qcasey/paperless_share#12]
Hi!

**Use Case**
I download a document which gets saved on the device (there is no way for sharing without downloading in the app). On Android a notification will appear when the download is completed. I press the notification and the document opens in the default app for that filetype or if there is none, ask the user to select an app which is able to open the document type. The document gets opened and I click the buttons to share the document with paperless share. 

**Improvement**
If the paperless share app would be associated with for example application/pdf I could upload the document by just clicking the notification and choosing to open the file with paperless share. This would reduce the needed clicks significantly. Same when browsing files in an explorer. 

**Details**
https://pub.dev/packages/flutter_handle_file should make it possible to implement this with minimal effort for both iOS and Android.
If only Android is relevant it should work by just adding some intent-filter properties in the AndroidManifest.xml. 
I guess some code to handle the file path is also needed. 

Would you be interested in this feature? If yes, are you interested in a PR for this or do you want to have a look at it yourself?

**Comment by qcasey** [comment]
I like this a lot! I'm always open to PRs. But I think it's a useful feature and would also add it myself in the next update (whenever that may be). 

If it's only a matter of changing the manifest, I'd consider other document types like .docx and .odt (as is supported by [paperless-ng](https://paperless-ng.readthedocs.io/en/latest/configuration.html#configuration-tika))

Thanks for including all the detail with your request.
