### ISSUE TITLE
13.01.2022 Update broke the App

### ISSUE THREAD

**Issue by mirisbowring** [qcasey/paperless_share#14]
Hi,

today, Google Play updated this app to the latest version.
After the Update, i cannot really start the app anymore.
After pressing the icon, the screen opens a blank, gray activity and does nothing else.

Same if i try to share a pdf via the app to my server. No circle loading or anything else. Just a blank gray screen.

**Comment by qcasey** [comment]
Hi, thank you for the report. I can't reproduce this on any of my devices.

This probably has to do with commit https://github.com/qcasey/paperless_share/commit/5db9224956b0e69d0fe35080b268a1e9fc8dee16

I'll just revert that for now.

**Comment by qcasey** [comment]
I pushed a new release to Google play just now. It'll be stuck in review for only a short time.

Please let me know if the patch fixes this issue for you once you get it.

**Comment by mirisbowring** [comment]
I will check and let you know. Thank you for the support!

**Comment by qcasey** [comment]
Having some issues with the release :roll_eyes: I can ping you when it's live if you'd like.

**Comment by danielr1996** [comment]
Downloading the apk and installing manually worked for me, I just had to uninstall the play store version before and do a fresh install.

**Comment by mirisbowring** [comment]
> Downloading the apk and installing manually worked for me, I just had to uninstall the play store version before and do a fresh install.

This was a very good hint!

I just removed the app and reinstalled from playstore... Now the latetst ", buggy" Version is working!


I also checked fdroid but the latest release on there is 8 month ago (1.0.6)

**Comment by qcasey** [comment]
Latest version is live and should have fixed this. I'll close and stop messing with the pages 🙈
