### ISSUE TITLE
Missing `PaperlessShare` in Share menu of Microsoft's apps

### ISSUE THREAD

**Issue by djpbessems** [qcasey/paperless_share#15]
I'm trying to use PaperlessShare straight from Microsoft's Office Lens, or from Microsoft's OneDrive, but the app does not show up amongst the available choices of the Share menu (even when scrolling through the whole list).

Other less-mainstream apps do show up (For instance Gotify or Stakali), so there must be a way to register PaperlessShare with Microsoft's own Share menu.

For reference, in other apps, I *am* seeing PaperlessShare in the Share menu

**Comment by qcasey** [comment]
Hello, thank you for reporting. 

It's a PDF, right? If you save it to your files and share it from there, does Paperless Share appear?

**Comment by djpbessems** [comment]
Yes, then it will show up.

I think I already figured out why the app is 'missing': it's due to that OneDrive and Office Lens are not sharing the actual file, but rather an URI to the file accessible through the OneDrive website...

**Comment by qcasey** [comment]
Ah yes that's probably why. I think I can work with that.

**Comment by qcasey** [comment]
I spoke too soon, that OneDrive share link can't be parsed since it points to their file hosting not to the original PDF.

For Office Lens specifically, I recommend tapping the file thumbnail (which downloads + opens the file) and sharing from there.
