### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by xschlef** [qcasey/paperless_share#3]
I'm cannot login with the app. There is no visible error.

The only thing I see are 403 responses from the paperless-ng webserver:
`
192.168.1.189 - - [06/Jan/2021:10:50:10 +0100] "POST /api/token/ HTTP/1.1" 403 1382 "-" "Dart/2.10 (dart:io)"
192.168.1.189 - - [06/Jan/2021:10:50:10 +0100] "POST /api/token/ HTTP/1.1" 403 1382 "-" "Dart/2.10 (dart:io)"
`

I'm using a standard docker-compose setup with up to date images.

**Comment by qcasey** [comment]
Hello, thank you for reporting.

Could you try logging in with my demo server?

**Server**: https://paperless-demo.quinncasey.com
**User**: demo
**Password**: demo

This will help me narrow down the issue

**Comment by qcasey** [comment]
More importantly - could you share the exact version of paperless-ng you're using? I'm able to induce this error on jonaswinkler/paperless-ng:0.9.4

This app uses token authentication which was introduced in 0.9.5, anything earlier won't work here.

**Comment by xschlef** [comment]
Whoops, so sorry. Did not take into account that my docker-compose file was not updated by git pull.. Sorry for the false alarm. I had 0.9.4 running....

**Comment by qcasey** [comment]
No worries! Enjoy
