### ISSUE TITLE
Paperless Share never completes upload

### ISSUE THREAD

**Issue by JSdeJong** [qcasey/paperless_share#4]
Adding my server to Paperless Share went without any issue. 
But when I share a PDF, jpeg or any other document the upload circle will spin but never stops. With small jpeg it will work.

The same behaviour is seen when using my exposed hostname (https via nginx) and using my internal server (http://<server>:8000)

I believe it doesn't have to do with client_max_body_size because without nginx the same issue occurs.
No lines are written in the paperless log when upload circle is spinning.

**Comment by qcasey** [comment]
Hello, thanks for reporting.

Two questions for you, when you're able - 

1. Which version of Paperless are you running? Paperless or Paperless-ng, and the version #?
2. Would you happen to have access to a computer with ADB :sweat_smile:? An `adb logcat | grep paperless` during the crash would be very helpful

**Comment by JSdeJong** [comment]
@qcasey Thanks for the reply. Surely I've tested it on two phones, and both had the same issue.
And I've done something, which included upgrading my unraid server, and meanwhile bought a new phone.. And everything seems to be working flawlessly.

So just ignore my issue. Probably myself to blame. Thanks for the software!

**Comment by FoxxMD** [comment]
I too am experiencing this. using paperless-ng 1.3.2, nothing showing in logs
